/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2013-11-16 11:17:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/index/../commons/taglib.jsp", Long.valueOf(1353591198096L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

response.setHeader("Pragma", "No-cache"); 
response.setHeader("Cache-Control", "no-cache");
response.setDateHeader("Expires", 0); 

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/index/index.css\" type=\"text/css\" rel=\"stylesheet\"></link>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/index/skdslider.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<title>仁安主页</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"contWith top\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"operater\">\r\n");
      out.write("\t\t\t<div class=\"oper\">\r\n");
      out.write("\t\t\t\t<a href=\"\">加入收藏</a>\r\n");
      out.write("\t\t\t\t&nbsp;|&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"\">设为首页</a>\r\n");
      out.write("\t\t\t\t&nbsp;|&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"\">联系我们</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t<span style=\"color: #655d5d\">联系电话：</span>\r\n");
      out.write("\t\t\t\t<span style=\"color: #df0611\">400-929-1020</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<div class=\"contWith\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/pages/index/index.jsp\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">仁安生态</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">仁安产品</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">仁安安全</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">生产安全</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">安全认证</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">郑总承若</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"liImg\" style=\"width: 2px;\"></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">质量追溯</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"container banner\" class=\"banner\">\r\n");
      out.write("\t\t<div id=\"coin-slider\" class=\"skdslider\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li id=\"pb1\"></li>\r\n");
      out.write("\t\t\t\t<li id=\"pb2\" ></li>\r\n");
      out.write("\t\t\t\t<li id=\"pb3\" ></li>\r\n");
      out.write("\t\t\t\t<li id=\"pb4\" ></li>\r\n");
      out.write("\t\t\t\t<li id=\"pb5\" ></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"contWith contentPanel\">\r\n");
      out.write("\t\t<div class=\"contBan conBanMar\">\r\n");
      out.write("\t\t\t<div class=\"contTitle renaanjj\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"conImg\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/conImg.jpg\" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<p style=\"color: #e76f16;font-size: 16px;line-height: 32px\">我们一直致力于做最好的生态禽业</p>\r\n");
      out.write("\t\t\t\t安徽太阳禽业有限公司位于美丽的黄山脚下，宁国市郊，成立于1996年5月。公司注册资本4200万元，是安徽省唯一专营樱桃谷系......\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"more moreJj\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"contBan conBanMar\">\r\n");
      out.write("\t\t\t<div class=\"contTitle renaanzxdt\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"conImg\">\r\n");
      out.write("\t\t\t\t<div class=\"comtentImg\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/wenz.jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"comtentTitle\">\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: 16px;color: #033d08;\">2013年人安农场成立</p>\r\n");
      out.write("\t\t\t\t\t<p>安徽太阳禽业有限公司位于美丽的黄山脚下系......</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\" style=\"width: 312px;\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/icon.png\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">安徽太阳禽业有限公司位于美丽的黄山脚下系</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p > 2013-11-29 20：00:00\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/icon.png\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">安徽太阳禽业有限公司位于美丽的黄山脚脚下</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p> 2013-11-29 20：00:00\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/icon.png\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">安徽太阳禽业有限公司位于美丽的黄山脚下脚</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p> 2013-11-29 20：00:00\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"more moreZx\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"contBan conBanMar\">\r\n");
      out.write("\t\t\t<div class=\"zhuis\">\r\n");
      out.write("\t\t\t\t<div class=\"zsInput\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" >\r\n");
      out.write("\t\t\t\t\t<div class=\"zsSearch\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"contTitle renaanlxwm\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\" style=\"width: 312px;line-height: 24px;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 15px;line-height: 28px;\">资兴市人安生态禽业有限公司</p>\t\r\n");
      out.write("\t\t\t\t<p>地址：资兴市人安生态禽业有限公司</p>\r\n");
      out.write("\t\t\t\t<p>\t电话：54151512-51512-152121</p>\r\n");
      out.write("\t\t\t\t<p>\t传真：5412121212</p>\r\n");
      out.write("\t\t\t\t<p>\tE-mail:451132132@qq.com</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"buttomOpe\">\r\n");
      out.write("\t\t<div class=\"contWith\" style=\"width: 1000px; \">\r\n");
      out.write("\t\t\t<div style=\"margin-top: 12px;margin-bottom: 4px;color: #ffffff;\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/home.png\"><span style=\"padding-left: 5px;\">资兴市XX路XX街道</span>\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/index/phone.png\" style=\"padding-left: 40px;\"><span  style=\"padding-left: 5px;\">0451215161-41521-42 </span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t<div class=\"buttonUl\">\r\n");
      out.write("\t\t\t\t<ul style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"margin-left: 0px;\"><a href=\"\">网站首页</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">创业加盟</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">资讯动态</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">生态养殖</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">在线留言</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"buliImg\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"clear\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"buttomInf\" >\r\n");
      out.write("\t\t<div class=\"contWith\" style=\"width: 1000px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span >版权所有：资兴市人安生态禽业有限公司</span>\r\n");
      out.write("\t\t\t<span  style=\"padding-left: 40px;\">技术支持：资兴市人安生态禽业有限公司 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/widgets/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/widgets/skdslider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\t\t$('#coin-slider').skdslider({'delay':5000, 'fadeSpeed': 2000,'autoStart':true});\r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /pages/index/../commons/taglib.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /pages/index/../commons/taglib.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath=='/'?'':pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /pages/index/../commons/taglib.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("checked");
    // /pages/index/../commons/taglib.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new String("checked=\"checked\""));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /pages/index/../commons/taglib.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("selected");
    // /pages/index/../commons/taglib.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new String("selected=\"selected\""));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }
}
