package com.ystech.aqtp.model;

// Generated 2013-11-28 22:36:43 by Hibernate Tools 4.0.0

/**
 * Access generated by hbm2java
 */
public class Access implements java.io.Serializable {

	private Integer dbid;
	private Integer access;

	public Access() {
	}

	public Access(Integer access) {
		this.access = access;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Integer getAccess() {
		return this.access;
	}

	public void setAccess(Integer access) {
		this.access = access;
	}

}
