package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Breed generated by hbm2java
 */
public class Breed implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String characteristic;
	private String note;
	private String charCode;
	private Set chickenbatches = new HashSet(0);

	public Breed() {
	}

	public Breed(String name, String characteristic, String note,
			String charCode, Set chickenbatches) {
		this.name = name;
		this.characteristic = characteristic;
		this.note = note;
		this.charCode = charCode;
		this.chickenbatches = chickenbatches;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCharacteristic() {
		return this.characteristic;
	}

	public void setCharacteristic(String characteristic) {
		this.characteristic = characteristic;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCharCode() {
		return this.charCode;
	}

	public void setCharCode(String charCode) {
		this.charCode = charCode;
	}

	public Set getChickenbatches() {
		return this.chickenbatches;
	}

	public void setChickenbatches(Set chickenbatches) {
		this.chickenbatches = chickenbatches;
	}

}
