package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chickenbatch generated by hbm2java
 */
public class ChickenBatch implements java.io.Serializable {

	private Integer dbid;
	private Breed breed;
	private Grade grade;
	private String batchNo;
	private String name;
	private Date birthday;
	private Integer age;
	private Date outBarDate;
	private Date intoBarDate;
	private Set healthcares = new HashSet(0);
	private Set breaderbreeds = new HashSet(0);
	private Set feedfeeders = new HashSet(0);
	private Set quarantinecertificates = new HashSet(0);
	private Set immunes = new HashSet(0);
	private Set dimensionas = new HashSet(0);

	public ChickenBatch() {
	}

	public ChickenBatch(Breed breed, Grade grade, String batchNo, String name,
			Date birthday, Integer age, Date outBarDate, Date intoBarDate,
			Set healthcares, Set breaderbreeds, Set feedfeeders,
			Set quarantinecertificates, Set immunes, Set dimensionas) {
		this.breed = breed;
		this.grade = grade;
		this.batchNo = batchNo;
		this.name = name;
		this.birthday = birthday;
		this.age = age;
		this.outBarDate = outBarDate;
		this.intoBarDate = intoBarDate;
		this.healthcares = healthcares;
		this.breaderbreeds = breaderbreeds;
		this.feedfeeders = feedfeeders;
		this.quarantinecertificates = quarantinecertificates;
		this.immunes = immunes;
		this.dimensionas = dimensionas;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Breed getBreed() {
		return this.breed;
	}

	public void setBreed(Breed breed) {
		this.breed = breed;
	}

	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getOutBarDate() {
		return this.outBarDate;
	}

	public void setOutBarDate(Date outBarDate) {
		this.outBarDate = outBarDate;
	}

	public Date getIntoBarDate() {
		return this.intoBarDate;
	}

	public void setIntoBarDate(Date intoBarDate) {
		this.intoBarDate = intoBarDate;
	}

	public Set getHealthcares() {
		return this.healthcares;
	}

	public void setHealthcares(Set healthcares) {
		this.healthcares = healthcares;
	}

	public Set getBreaderbreeds() {
		return this.breaderbreeds;
	}

	public void setBreaderbreeds(Set breaderbreeds) {
		this.breaderbreeds = breaderbreeds;
	}

	public Set getFeedfeeders() {
		return this.feedfeeders;
	}

	public void setFeedfeeders(Set feedfeeders) {
		this.feedfeeders = feedfeeders;
	}

	public Set getQuarantinecertificates() {
		return this.quarantinecertificates;
	}

	public void setQuarantinecertificates(Set quarantinecertificates) {
		this.quarantinecertificates = quarantinecertificates;
	}

	public Set getImmunes() {
		return this.immunes;
	}

	public void setImmunes(Set immunes) {
		this.immunes = immunes;
	}

	public Set getDimensionas() {
		return this.dimensionas;
	}

	public void setDimensionas(Set dimensionas) {
		this.dimensionas = dimensionas;
	}

}
