package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

/**
 * Feedfeeder generated by hbm2java
 */
public class FeedFeeder implements java.io.Serializable {

	private Integer dbid;
	private Feeder feeder;
	private ChickenBatch chickenbatch;
	private String name;

	public FeedFeeder() {
	}

	public FeedFeeder(Feeder feeder, ChickenBatch chickenbatch, String name) {
		this.feeder = feeder;
		this.chickenbatch = chickenbatch;
		this.name = name;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Feeder getFeeder() {
		return this.feeder;
	}

	public void setFeeder(Feeder feeder) {
		this.feeder = feeder;
	}

	public ChickenBatch getChickenbatch() {
		return this.chickenbatch;
	}

	public void setChickenbatch(ChickenBatch chickenbatch) {
		this.chickenbatch = chickenbatch;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
