package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String level;
	private String note;
	private Float retailPrice;
	private Set chickenbatches = new HashSet(0);

	public Grade() {
	}

	public Grade(String name, String level, String note, Float retailPrice,
			Set chickenbatches) {
		this.name = name;
		this.level = level;
		this.note = note;
		this.retailPrice = retailPrice;
		this.chickenbatches = chickenbatches;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Float getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(Float retailPrice) {
		this.retailPrice = retailPrice;
	}

	public Set getChickenbatches() {
		return this.chickenbatches;
	}

	public void setChickenbatches(Set chickenbatches) {
		this.chickenbatches = chickenbatches;
	}

}
