package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

/**
 * Immunedrag generated by hbm2java
 */
public class ImmuneDrag implements java.io.Serializable {

	private Integer dbid;
	private Drag drag;
	private Immune immune;
	private String name;
	private String dose;

	public ImmuneDrag() {
	}

	public ImmuneDrag(Drag drag, Immune immune, String name, String dose) {
		this.drag = drag;
		this.immune = immune;
		this.name = name;
		this.dose = dose;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public Drag getDrag() {
		return this.drag;
	}

	public void setDrag(Drag drag) {
		this.drag = drag;
	}

	public Immune getImmune() {
		return this.immune;
	}

	public void setImmune(Immune immune) {
		this.immune = immune;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

}
