package com.ystech.aqtp.model;

// Generated 2013-11-12 15:43:35 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer dbid;
	private NewsType newstype;
	private String title;
	private String content;
	private String contentText;
	private User releasePerson;
	private Date releaseDate;
	private Integer readNum;
	private Boolean isBannerPicture;//是否为图片新闻
	private Boolean isTitlePicture;//是否标题图片新闻
	private Boolean isOnTime;//是否是实时要闻
	private Boolean isLatestNew;//是否为最新动态
	private Boolean isStop;//新闻是否停用
	private String titlePicture;//标题图片
	private String bannerPicture;//banner图片
	private String attach;
	private String introduction;

	public News() {
	}

	public News(int dbid, String title) {
		this.dbid = dbid;
		this.title = title;
	}

	public News(int dbid, NewsType newstype, String title, String content,
			Integer releasePerson, Date releaseDate, Integer readNum,
			Boolean isPicture, Boolean isOnTime, Boolean isLatestNew,
			String titlePicture) {
		this.dbid = dbid;
		this.newstype = newstype;
		this.title = title;
		this.content = content;
		this.releaseDate = releaseDate;
		this.readNum = readNum;
		this.isOnTime = isOnTime;
		this.isLatestNew = isLatestNew;
		this.titlePicture = titlePicture;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public NewsType getNewstype() {
		return this.newstype;
	}

	public void setNewstype(NewsType newstype) {
		this.newstype = newstype;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public User getReleasePerson() {
		return releasePerson;
	}

	public void setReleasePerson(User releasePerson) {
		this.releasePerson = releasePerson;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Integer getReadNum() {
		return this.readNum;
	}

	public void setReadNum(Integer readNum) {
		this.readNum = readNum;
	}


	public Boolean getIsBannerPicture() {
		return isBannerPicture;
	}

	public void setIsBannerPicture(Boolean isBannerPicture) {
		this.isBannerPicture = isBannerPicture;
	}

	public Boolean getIsOnTime() {
		return this.isOnTime;
	}

	public void setIsOnTime(Boolean isOnTime) {
		this.isOnTime = isOnTime;
	}

	public Boolean getIsLatestNew() {
		return this.isLatestNew;
	}

	public void setIsLatestNew(Boolean isLatestNew) {
		this.isLatestNew = isLatestNew;
	}

	public String getTitlePicture() {
		return this.titlePicture;
	}

	public void setTitlePicture(String titlePicture) {
		this.titlePicture = titlePicture;
	}

	public Boolean getIsStop() {
		return isStop;
	}

	public void setIsStop(Boolean isStop) {
		this.isStop = isStop;
	}

	public String getAttach() {
		return attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}

	public String getBannerPicture() {
		return bannerPicture;
	}

	public void setBannerPicture(String bannerPicture) {
		this.bannerPicture = bannerPicture;
	}

	public Boolean getIsTitlePicture() {
		return isTitlePicture;
	}

	public void setIsTitlePicture(Boolean isTitlePicture) {
		this.isTitlePicture = isTitlePicture;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getContentText() {
		return contentText;
	}

	public void setContentText(String contentText) {
		this.contentText = contentText;
	}

}
