package com.ystech.aqtp.model;

// Generated 2013-7-10 22:53:17 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Operatelog generated by hbm2java
 */
public class OperateLog implements java.io.Serializable {

	private Integer dbid;
	private String operator;
	private Date operatedate;
	private String operateobj;
	private String operatetype;
	private Integer userId;
	private String operatefeild;
	private String ipAddress;

	public OperateLog() {
	}

	public OperateLog(String operator, Date operatedate, String operateobj,
			String operatetype, Integer userId, String operatefeild,
			String ipAddress) {
		this.operator = operator;
		this.operatedate = operatedate;
		this.operateobj = operateobj;
		this.operatetype = operatetype;
		this.userId = userId;
		this.operatefeild = operatefeild;
		this.ipAddress = ipAddress;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getOperatedate() {
		return this.operatedate;
	}

	public void setOperatedate(Date operatedate) {
		this.operatedate = operatedate;
	}

	public String getOperateobj() {
		return this.operateobj;
	}

	public void setOperateobj(String operateobj) {
		this.operateobj = operateobj;
	}

	public String getOperatetype() {
		return this.operatetype;
	}

	public void setOperatetype(String operatetype) {
		this.operatetype = operatetype;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getOperatefeild() {
		return this.operatefeild;
	}

	public void setOperatefeild(String operatefeild) {
		this.operatefeild = operatefeild;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
