package com.ystech.aqtp.model;

// Generated 2013-6-22 16:47:10 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Quarantinecertificate generated by hbm2java
 */
public class QuarantineCertificate implements java.io.Serializable {

	private Integer dbid;
	private ChickenBatch chickenbatch;
	private String awardGroup;
	private Date awardDate;
	private String certificateImage;
	private String note;
	private String title;

	public QuarantineCertificate() {
	}

	public QuarantineCertificate(ChickenBatch chickenbatch, String awardGroup,
			Date awardDate, String certificateImage, String note, String title) {
		this.chickenbatch = chickenbatch;
		this.awardGroup = awardGroup;
		this.awardDate = awardDate;
		this.certificateImage = certificateImage;
		this.note = note;
		this.title = title;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public ChickenBatch getChickenbatch() {
		return this.chickenbatch;
	}

	public void setChickenbatch(ChickenBatch chickenbatch) {
		this.chickenbatch = chickenbatch;
	}

	public String getAwardGroup() {
		return this.awardGroup;
	}

	public void setAwardGroup(String awardGroup) {
		this.awardGroup = awardGroup;
	}

	public Date getAwardDate() {
		return this.awardDate;
	}

	public void setAwardDate(Date awardDate) {
		this.awardDate = awardDate;
	}

	public String getCertificateImage() {
		return this.certificateImage;
	}

	public void setCertificateImage(String certificateImage) {
		this.certificateImage = certificateImage;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
